-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.log_guia
(
    id bigserial NOT NULL,
    id_trs_guia_remision uuid NOT NULL,
    id_mae_empresa uuid NOT NULL,
    id_mae_usuario uuid,
    accion character varying(50) COLLATE pg_catalog."default" NOT NULL,
    estado_anterior estado_guia,
    estado_nuevo estado_guia,
    detalle jsonb,
    ip_address inet,
    user_agent character varying(500) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_log_guia PRIMARY KEY (id, created_at)
);

COMMENT ON TABLE public.log_guia
    IS 'Log de auditoría de todas las operaciones sobre guías de remisión. Particionado por año.';

COMMENT ON COLUMN public.log_guia.accion
    IS 'Valores esperados: CREAR, EDITAR, CAMBIO_ESTADO, ANULAR, ENVIAR_SUNAT, REENVIAR_SUNAT.';

COMMENT ON COLUMN public.log_guia.detalle
    IS 'Payload JSONB libre: datos adicionales del evento (antes/después, errores, etc.).';

CREATE TABLE IF NOT EXISTS public.mae_conductor
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_persona uuid NOT NULL,
    id_mae_empresa uuid,
    licencia_tipo character varying(5) COLLATE pg_catalog."default" NOT NULL,
    licencia_numero character varying(20) COLLATE pg_catalog."default" NOT NULL,
    licencia_vencimiento date NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_conductor PRIMARY KEY (id),
    CONSTRAINT uq_mae_conductor_licencia UNIQUE (licencia_numero)
);

COMMENT ON TABLE public.mae_conductor
    IS 'Conductores habilitados para transporte de carga.';

COMMENT ON COLUMN public.mae_conductor.licencia_tipo
    IS 'Categoría MTC (A1, A2a, A2b, A3a, A3b, B2c, etc.).';

COMMENT ON COLUMN public.mae_conductor.licencia_vencimiento
    IS 'Fecha de vencimiento de la licencia de conducir.';

CREATE TABLE IF NOT EXISTS public.mae_empresa
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    ruc character(11) COLLATE pg_catalog."default" NOT NULL,
    razon_social character varying(200) COLLATE pg_catalog."default" NOT NULL,
    nombre_comercial character varying(200) COLLATE pg_catalog."default",
    direccion_fiscal character varying(300) COLLATE pg_catalog."default" NOT NULL,
    id_mae_ubigeo character(6) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    logo_url character varying(500) COLLATE pg_catalog."default",
    sol_usuario character varying(20) COLLATE pg_catalog."default",
    sol_password_enc character varying(500) COLLATE pg_catalog."default",
    cert_digital_path character varying(500) COLLATE pg_catalog."default",
    cert_password_enc character varying(500) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_empresa PRIMARY KEY (id),
    CONSTRAINT uq_mae_empresa_ruc UNIQUE (ruc)
);

ALTER TABLE IF EXISTS public.mae_empresa
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.mae_empresa
    IS 'Empresas habilitadas para emitir guías de remisión electrónicas.';

COMMENT ON COLUMN public.mae_empresa.ruc
    IS 'RUC de 11 dígitos (SUNAT).';

COMMENT ON COLUMN public.mae_empresa.sol_password_enc
    IS 'Contraseña SOL cifrada con AES-256-GCM. La capa de aplicación gestiona el descifrado.';

COMMENT ON COLUMN public.mae_empresa.cert_password_enc
    IS 'Passphrase del certificado digital, cifrada.';

CREATE TABLE IF NOT EXISTS public.mae_establecimiento
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid NOT NULL,
    codigo character varying(4) COLLATE pg_catalog."default" NOT NULL,
    denominacion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(300) COLLATE pg_catalog."default" NOT NULL,
    id_mae_ubigeo character(6) COLLATE pg_catalog."default" NOT NULL,
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    es_principal boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_establecimiento PRIMARY KEY (id),
    CONSTRAINT uq_mae_establecimiento_codigo UNIQUE (id_mae_empresa, codigo)
);

COMMENT ON TABLE public.mae_establecimiento
    IS 'Establecimientos / puntos de venta registrados ante SUNAT.';

COMMENT ON COLUMN public.mae_establecimiento.codigo
    IS 'Código de 4 dígitos asignado por SUNAT (ej: 0000 = casa matriz).';

COMMENT ON COLUMN public.mae_establecimiento.es_principal
    IS 'TRUE = establecimiento principal (casa matriz).';

CREATE TABLE IF NOT EXISTS public.mae_persona
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid,
    tipo_doc tipo_documento_identidad NOT NULL DEFAULT '6'::tipo_documento_identidad,
    num_doc character varying(20) COLLATE pg_catalog."default" NOT NULL,
    razon_social character varying(200) COLLATE pg_catalog."default",
    nombre character varying(100) COLLATE pg_catalog."default",
    apellido_paterno character varying(100) COLLATE pg_catalog."default",
    apellido_materno character varying(100) COLLATE pg_catalog."default",
    direccion character varying(300) COLLATE pg_catalog."default",
    id_mae_ubigeo character(6) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    es_cliente boolean NOT NULL DEFAULT false,
    es_proveedor boolean NOT NULL DEFAULT false,
    activo boolean NOT NULL DEFAULT true,
    ts_busqueda tsvector GENERATED ALWAYS AS (to_tsvector('simple'::regconfig, fn_unaccent_immutable((((((((((COALESCE(razon_social, ''::character varying))::text || ' '::text) || (COALESCE(nombre, ''::character varying))::text) || ' '::text) || (COALESCE(apellido_paterno, ''::character varying))::text) || ' '::text) || (COALESCE(apellido_materno, ''::character varying))::text) || ' '::text) || (COALESCE(num_doc, ''::character varying))::text)))) STORED,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_persona PRIMARY KEY (id),
    CONSTRAINT uq_mae_persona_doc UNIQUE (tipo_doc, num_doc, id_mae_empresa)
);

ALTER TABLE IF EXISTS public.mae_persona
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.mae_persona
    IS 'Personas naturales y jurídicas: clientes, proveedores, remitentes y destinatarios.';

COMMENT ON COLUMN public.mae_persona.id_mae_empresa
    IS 'NULL indica persona compartida entre todas las empresas del sistema.';

COMMENT ON COLUMN public.mae_persona.ts_busqueda
    IS 'Vector full-text generado automáticamente a partir de nombre/razón social y documento.';

CREATE TABLE IF NOT EXISTS public.mae_plan_cuentas
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid NOT NULL,
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    denominacion character varying(200) COLLATE pg_catalog."default" NOT NULL,
    id_padre uuid,
    nivel smallint NOT NULL DEFAULT 1,
    naturaleza character(1) COLLATE pg_catalog."default",
    acepta_movimiento boolean NOT NULL DEFAULT true,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_plan_cuentas PRIMARY KEY (id),
    CONSTRAINT uq_mae_plan_cuentas_codigo UNIQUE (id_mae_empresa, codigo)
);

COMMENT ON TABLE public.mae_plan_cuentas
    IS 'Plan de cuentas contable (PCGE), estructura jerárquica por empresa.';

COMMENT ON COLUMN public.mae_plan_cuentas.codigo
    IS 'Código de cuenta PCGE (ej: 601, 4011, 1011).';

COMMENT ON COLUMN public.mae_plan_cuentas.id_padre
    IS 'Cuenta padre en la jerarquía (NULL si es cuenta de primer nivel).';

COMMENT ON COLUMN public.mae_plan_cuentas.naturaleza
    IS 'D = Deudora (Activo/Gasto), A = Acreedora (Pasivo/Patrimonio/Ingreso).';

COMMENT ON COLUMN public.mae_plan_cuentas.acepta_movimiento
    IS 'FALSE indica cuenta agrupadora/totalizadora, no se le registran asientos directos.';

CREATE TABLE IF NOT EXISTS public.mae_producto
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid NOT NULL,
    codigo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    unidad_medida character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NIU'::character varying,
    peso_unitario numeric(12, 3),
    precio_referencial numeric(12, 2),
    id_mae_plan_cuentas uuid,
    stock_actual numeric(14, 3) NOT NULL DEFAULT 0,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_producto PRIMARY KEY (id),
    CONSTRAINT uq_mae_producto_codigo UNIQUE (id_mae_empresa, codigo)
);

COMMENT ON TABLE public.mae_producto
    IS 'Catálogo de productos/mercadería de la empresa.';

COMMENT ON COLUMN public.mae_producto.unidad_medida
    IS 'Código SUNAT catálogo N° 3: NIU (unidad), KGM (kg), LTR (litro), etc.';

COMMENT ON COLUMN public.mae_producto.id_mae_plan_cuentas
    IS 'Cuenta contable de inventario/compra asociada (opcional, para integración contable).';

COMMENT ON COLUMN public.mae_producto.stock_actual
    IS 'Saldo de inventario actual. Se actualiza desde los módulos de compra/venta/traslado.';

CREATE TABLE IF NOT EXISTS public.mae_serie_documento
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_establecimiento uuid NOT NULL,
    tipo_doc character varying(3) COLLATE pg_catalog."default" NOT NULL,
    serie character(4) COLLATE pg_catalog."default" NOT NULL,
    correlativo_actual integer NOT NULL DEFAULT 0,
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_serie_documento PRIMARY KEY (id),
    CONSTRAINT uq_mae_serie_documento UNIQUE (id_mae_establecimiento, tipo_doc, serie)
);

COMMENT ON TABLE public.mae_serie_documento
    IS 'Control de series y correlativos por tipo de documento y establecimiento.';

COMMENT ON COLUMN public.mae_serie_documento.tipo_doc
    IS 'T09 = Guía Remitente; T31 = Guía Transportista.';

COMMENT ON COLUMN public.mae_serie_documento.serie
    IS 'Formato: letra + 3 dígitos (T001, V002, etc.).';

COMMENT ON COLUMN public.mae_serie_documento.correlativo_actual
    IS 'Último correlativo emitido. La función fn_siguiente_correlativo lo incrementa con bloqueo.';

CREATE TABLE IF NOT EXISTS public.mae_ubigeo
(
    id character(6) COLLATE pg_catalog."default" NOT NULL,
    departamento character varying(100) COLLATE pg_catalog."default" NOT NULL,
    provincia character varying(100) COLLATE pg_catalog."default" NOT NULL,
    distrito character varying(100) COLLATE pg_catalog."default" NOT NULL,
    codigo_postal character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT pk_mae_ubigeo PRIMARY KEY (id)
);

COMMENT ON TABLE public.mae_ubigeo
    IS 'Catálogo de ubigeos del Perú según INEI (formato DDPPDD).';

COMMENT ON COLUMN public.mae_ubigeo.id
    IS 'Código de 6 dígitos: 2 dpto + 2 prov + 2 distrito.';

COMMENT ON COLUMN public.mae_ubigeo.departamento
    IS 'Nombre del departamento / región.';

COMMENT ON COLUMN public.mae_ubigeo.provincia
    IS 'Nombre de la provincia.';

COMMENT ON COLUMN public.mae_ubigeo.distrito
    IS 'Nombre del distrito.';

COMMENT ON COLUMN public.mae_ubigeo.codigo_postal
    IS 'Código postal (opcional).';

CREATE TABLE IF NOT EXISTS public.mae_usuario
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid NOT NULL,
    nombre_completo character varying(200) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(200) COLLATE pg_catalog."default" NOT NULL,
    rol rol_usuario NOT NULL DEFAULT 'OPERADOR'::rol_usuario,
    activo boolean NOT NULL DEFAULT true,
    ultimo_acceso timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_usuario PRIMARY KEY (id),
    CONSTRAINT uq_mae_usuario_email UNIQUE (id_mae_empresa, email)
);

ALTER TABLE IF EXISTS public.mae_usuario
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.mae_usuario
    IS 'Usuarios del sistema, aislados por empresa (multi-tenant).';

COMMENT ON COLUMN public.mae_usuario.password_hash
    IS 'Hash de contraseña. Usar Argon2id o bcrypt — nunca MD5/SHA1.';

COMMENT ON COLUMN public.mae_usuario.rol
    IS 'ADMIN > SUPERVISOR > OPERADOR > CONSULTA.';

CREATE TABLE IF NOT EXISTS public.mae_vehiculo
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid NOT NULL,
    marca character varying(50) COLLATE pg_catalog."default" NOT NULL,
    modelo character varying(100) COLLATE pg_catalog."default",
    placa character varying(10) COLLATE pg_catalog."default" NOT NULL,
    anio smallint,
    color character varying(30) COLLATE pg_catalog."default",
    activo boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_mae_vehiculo PRIMARY KEY (id),
    CONSTRAINT uq_mae_vehiculo_placa UNIQUE (id_mae_empresa, placa)
);

COMMENT ON TABLE public.mae_vehiculo
    IS 'Vehículos registrados para el traslado de mercadería.';

COMMENT ON COLUMN public.mae_vehiculo.placa
    IS 'Placa vehicular — formatos: ABC-123 (antiguo) o A1B234 (nuevo).';

CREATE TABLE IF NOT EXISTS public.trs_guia_detalle
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_trs_guia_remision uuid NOT NULL,
    linea smallint NOT NULL,
    codigo_producto character varying(50) COLLATE pg_catalog."default",
    descripcion character varying(500) COLLATE pg_catalog."default" NOT NULL,
    cantidad numeric(12, 3) NOT NULL,
    unidad_medida character varying(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'NIU'::character varying,
    peso_unitario numeric(12, 3),
    peso_total numeric(12, 3) GENERATED ALWAYS AS (
CASE
    WHEN (peso_unitario IS NOT NULL) THEN round((cantidad * peso_unitario), 3)
    ELSE NULL::numeric
END) STORED,
    lote character varying(50) COLLATE pg_catalog."default",
    fecha_vencimiento date,
    serie_item character varying(100) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_trs_guia_detalle PRIMARY KEY (id),
    CONSTRAINT uq_trs_guia_detalle_linea UNIQUE (id_trs_guia_remision, linea)
);

ALTER TABLE IF EXISTS public.trs_guia_detalle
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.trs_guia_detalle
    IS 'Detalle de bienes / productos incluidos en la guía de remisión.';

COMMENT ON COLUMN public.trs_guia_detalle.unidad_medida
    IS 'Código SUNAT catálogo N° 3: NIU (unidad), KGM (kg), LTR (litro), etc.';

COMMENT ON COLUMN public.trs_guia_detalle.peso_total
    IS 'Calculado automáticamente: ROUND(cantidad × peso_unitario, 3).';

COMMENT ON COLUMN public.trs_guia_detalle.lote
    IS 'Número de lote para trazabilidad (alimentos, farma, etc.).';

CREATE TABLE IF NOT EXISTS public.trs_guia_referencia
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_trs_guia_remision uuid NOT NULL,
    tipo_doc tipo_doc_referencia NOT NULL,
    serie character(4) COLLATE pg_catalog."default" NOT NULL,
    correlativo character varying(8) COLLATE pg_catalog."default" NOT NULL,
    fecha_emision date,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_trs_guia_referencia PRIMARY KEY (id),
    CONSTRAINT uq_trs_guia_referencia UNIQUE (id_trs_guia_remision, tipo_doc, serie, correlativo)
);

COMMENT ON TABLE public.trs_guia_referencia
    IS 'Documentos de referencia vinculados a la guía (facturas, boletas, OC, otras guías).';

CREATE TABLE IF NOT EXISTS public.trs_guia_remision
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_mae_empresa uuid NOT NULL,
    id_mae_establecimiento uuid NOT NULL,
    serie character(4) COLLATE pg_catalog."default" NOT NULL,
    correlativo character varying(8) COLLATE pg_catalog."default" NOT NULL,
    numero_completo character varying(15) COLLATE pg_catalog."default" GENERATED ALWAYS AS ((((serie)::text || '-'::text) || (correlativo)::text)) STORED,
    fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
    fecha_inicio_traslado date NOT NULL,
    motivo_traslado motivo_traslado NOT NULL,
    descripcion_motivo character varying(500) COLLATE pg_catalog."default",
    modalidad_transporte modalidad_transporte NOT NULL,
    id_mae_persona_remitente uuid NOT NULL,
    id_mae_persona_destinatario uuid NOT NULL,
    direccion_partida character varying(300) COLLATE pg_catalog."default" NOT NULL,
    id_mae_ubigeo_partida character(6) COLLATE pg_catalog."default" NOT NULL,
    direccion_llegada character varying(300) COLLATE pg_catalog."default" NOT NULL,
    id_mae_ubigeo_llegada character(6) COLLATE pg_catalog."default" NOT NULL,
    peso_bruto_total numeric(12, 3) NOT NULL,
    unidad_peso unidad_peso NOT NULL DEFAULT 'KGM'::unidad_peso,
    num_bultos integer,
    hash_cpe character varying(500) COLLATE pg_catalog."default",
    xml_firmado text COLLATE pg_catalog."default",
    cdr_sunat text COLLATE pg_catalog."default",
    codigo_respuesta_sunat character varying(5) COLLATE pg_catalog."default",
    descripcion_sunat character varying(500) COLLATE pg_catalog."default",
    qr_code text COLLATE pg_catalog."default",
    estado estado_guia NOT NULL DEFAULT 'BORRADOR'::estado_guia,
    observaciones character varying(1000) COLLATE pg_catalog."default",
    id_mae_usuario uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    enviado_at timestamp with time zone,
    anulado_at timestamp with time zone,
    motivo_anulacion character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT pk_trs_guia_remision PRIMARY KEY (id),
    CONSTRAINT uq_trs_guia_numero UNIQUE (id_mae_empresa, serie, correlativo)
);

ALTER TABLE IF EXISTS public.trs_guia_remision
    ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.trs_guia_remision
    IS 'Documento principal: Guía de Remisión Electrónica — Remitente (GRE).';

COMMENT ON COLUMN public.trs_guia_remision.numero_completo
    IS 'SERIE-CORRELATIVO generado (ej: T001-00000001). No editable.';

COMMENT ON COLUMN public.trs_guia_remision.hash_cpe
    IS 'Resumen SHA-256 del comprobante para validación SUNAT.';

COMMENT ON COLUMN public.trs_guia_remision.xml_firmado
    IS 'XML UBL 2.1 firmado digitalmente con certificado de la empresa.';

COMMENT ON COLUMN public.trs_guia_remision.cdr_sunat
    IS 'CDR (Constancia de Recepción) devuelta por SUNAT.';

COMMENT ON COLUMN public.trs_guia_remision.codigo_respuesta_sunat
    IS '0 = aceptado; otro código = observado/rechazado.';

CREATE TABLE IF NOT EXISTS public.trs_guia_transportista
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    id_trs_guia_remision uuid NOT NULL,
    id_mae_vehiculo uuid,
    id_mae_conductor uuid,
    ruc_transportista character(11) COLLATE pg_catalog."default",
    razon_social_transportista character varying(200) COLLATE pg_catalog."default",
    placa_manual character varying(10) COLLATE pg_catalog."default",
    licencia_manual character varying(20) COLLATE pg_catalog."default",
    tipo_doc_conductor tipo_documento_identidad,
    num_doc_conductor character varying(20) COLLATE pg_catalog."default",
    nombre_conductor character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_trs_guia_transportista PRIMARY KEY (id),
    CONSTRAINT uq_trs_guia_transportista UNIQUE (id_trs_guia_remision)
);

COMMENT ON TABLE public.trs_guia_transportista
    IS 'Transportista asignado a la guía: puede ser interno (id_mae_vehiculo/id_mae_conductor) o externo (datos manuales).';

ALTER TABLE IF EXISTS public.mae_conductor
    ADD CONSTRAINT fk_mae_conductor_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_conductor
    ADD CONSTRAINT fk_mae_conductor_persona FOREIGN KEY (id_mae_persona)
    REFERENCES public.mae_persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_empresa
    ADD CONSTRAINT fk_mae_empresa_ubigeo FOREIGN KEY (id_mae_ubigeo)
    REFERENCES public.mae_ubigeo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_establecimiento
    ADD CONSTRAINT fk_mae_establecimiento_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_mae_establecimiento_empresa
    ON public.mae_establecimiento(id_mae_empresa);


ALTER TABLE IF EXISTS public.mae_establecimiento
    ADD CONSTRAINT fk_mae_establecimiento_ubigeo FOREIGN KEY (id_mae_ubigeo)
    REFERENCES public.mae_ubigeo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_persona
    ADD CONSTRAINT fk_mae_persona_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_mae_persona_empresa
    ON public.mae_persona(id_mae_empresa);


ALTER TABLE IF EXISTS public.mae_persona
    ADD CONSTRAINT fk_mae_persona_ubigeo FOREIGN KEY (id_mae_ubigeo)
    REFERENCES public.mae_ubigeo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_plan_cuentas
    ADD CONSTRAINT fk_mae_plan_cuentas_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_plan_cuentas
    ADD CONSTRAINT fk_mae_plan_cuentas_padre FOREIGN KEY (id_padre)
    REFERENCES public.mae_plan_cuentas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_mae_plan_cuentas_padre
    ON public.mae_plan_cuentas(id_padre);


ALTER TABLE IF EXISTS public.mae_producto
    ADD CONSTRAINT fk_mae_producto_cuenta FOREIGN KEY (id_mae_plan_cuentas)
    REFERENCES public.mae_plan_cuentas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_mae_producto_cuenta
    ON public.mae_producto(id_mae_plan_cuentas);


ALTER TABLE IF EXISTS public.mae_producto
    ADD CONSTRAINT fk_mae_producto_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_serie_documento
    ADD CONSTRAINT fk_mae_serie_establecimiento FOREIGN KEY (id_mae_establecimiento)
    REFERENCES public.mae_establecimiento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_usuario
    ADD CONSTRAINT fk_mae_usuario_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mae_vehiculo
    ADD CONSTRAINT fk_mae_vehiculo_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trs_guia_detalle
    ADD CONSTRAINT fk_trs_guia_detalle_guia FOREIGN KEY (id_trs_guia_remision)
    REFERENCES public.trs_guia_remision (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_trs_guia_detalle_guia
    ON public.trs_guia_detalle(id_trs_guia_remision);


ALTER TABLE IF EXISTS public.trs_guia_referencia
    ADD CONSTRAINT fk_trs_guia_ref_guia FOREIGN KEY (id_trs_guia_remision)
    REFERENCES public.trs_guia_remision (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_trs_guia_referencia_guia
    ON public.trs_guia_referencia(id_trs_guia_remision);


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_destinatario FOREIGN KEY (id_mae_persona_destinatario)
    REFERENCES public.mae_persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_trs_guia_destinatario
    ON public.trs_guia_remision(id_mae_persona_destinatario);


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_empresa FOREIGN KEY (id_mae_empresa)
    REFERENCES public.mae_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_establecimiento FOREIGN KEY (id_mae_establecimiento)
    REFERENCES public.mae_establecimiento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_remitente FOREIGN KEY (id_mae_persona_remitente)
    REFERENCES public.mae_persona (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_trs_guia_remitente
    ON public.trs_guia_remision(id_mae_persona_remitente);


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_ubigeo_llegada FOREIGN KEY (id_mae_ubigeo_llegada)
    REFERENCES public.mae_ubigeo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_ubigeo_partida FOREIGN KEY (id_mae_ubigeo_partida)
    REFERENCES public.mae_ubigeo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trs_guia_remision
    ADD CONSTRAINT fk_trs_guia_usuario FOREIGN KEY (id_mae_usuario)
    REFERENCES public.mae_usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.trs_guia_transportista
    ADD CONSTRAINT fk_trs_guia_transp_conductor FOREIGN KEY (id_mae_conductor)
    REFERENCES public.mae_conductor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_trs_guia_transportista_conductor
    ON public.trs_guia_transportista(id_mae_conductor);


ALTER TABLE IF EXISTS public.trs_guia_transportista
    ADD CONSTRAINT fk_trs_guia_transp_guia FOREIGN KEY (id_trs_guia_remision)
    REFERENCES public.trs_guia_remision (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_trs_guia_transportista
    ON public.trs_guia_transportista(id_trs_guia_remision);


ALTER TABLE IF EXISTS public.trs_guia_transportista
    ADD CONSTRAINT fk_trs_guia_transp_vehiculo FOREIGN KEY (id_mae_vehiculo)
    REFERENCES public.mae_vehiculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_trs_guia_transportista_vehiculo
    ON public.trs_guia_transportista(id_mae_vehiculo);

END;